import Link from 'next/link';
import { CATEGORY_LABELS, CATEGORIES } from '@/lib/types';
import embedded from '@/data/resources.embedded.json';

export const metadata = {
  title: 'About UW Compass',
  description:
    'How UW Compass works: motivation, architecture, AI integration, and a guide to using the app.',
};

const RESOURCE_COUNT = (embedded as unknown[]).length;

export default function AboutPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-10">
      <nav className="mb-8 flex items-center justify-between text-sm">
        <Link href="/" className="font-semibold text-husky-purple hover:underline">
          ← UW Compass
        </Link>
        <a
          href="https://github.com/aryank09/UW-Compass"
          target="_blank"
          rel="noreferrer"
          className="text-slate-500 hover:text-husky-purple hover:underline"
        >
          GitHub repository ↗
        </a>
      </nav>

      <header className="mb-10">
        <h1 className="text-3xl font-bold tracking-tight text-husky-purple">About UW Compass</h1>
        <p className="mt-2 text-slate-600">
          A CSS 382 (Intro to AI) project that helps UW students find the right campus resource by
          describing their situation in plain language.
        </p>
      </header>

      <Section title="Overview & motivation">
        <p>
          UW has more support services than most students know about — tutoring, counseling, food
          security, transportation, study spaces, career help, financial aid. The problem isn't
          availability; it's <strong>fragmentation</strong>. Each office runs its own site, its own
          intake form, its own vocabulary. A student in trouble usually knows what's going wrong
          ("I'm overwhelmed and behind in math"), not which office to email.
        </p>
        <p>
          UW Compass closes that gap. You type your situation in your own words. The app extracts
          the underlying needs, matches them against a curated set of {RESOURCE_COUNT} official UW
          resources, and gives you ranked recommendations with a short action plan.
        </p>
      </Section>

      <Section title="UW community impact">
        <p>
          The students hit hardest by resource fragmentation are usually the ones with the least
          time to navigate it: first-year students, transfer students, commuters, and students
          juggling academic, financial, and wellness pressure at once. UW Compass benefits them by:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>reducing the time students spend searching for help;</li>
          <li>making existing UW services easier to discover;</li>
          <li>letting students describe needs in plain language instead of office names;</li>
          <li>providing short summaries and direct next-step recommendations;</li>
          <li>supporting students who are overwhelmed and need a clearer path to action.</li>
        </ul>
        <p>
          UW Compass <em>does not replace</em> official UW resources. Every recommendation links
          out to the corresponding UW office or page. It's a routing layer, not a service of its
          own. For emergencies, students are pointed at{' '}
          <a
            href="https://www.washington.edu/safecampus/"
            className="text-husky-purple underline"
            target="_blank"
            rel="noreferrer"
          >
            SafeCampus
          </a>{' '}
          and the{' '}
          <a
            href="https://wellbeing.uw.edu/counseling-center/husky-helpline/"
            className="text-husky-purple underline"
            target="_blank"
            rel="noreferrer"
          >
            Husky HelpLine (24/7)
          </a>
          .
        </p>
      </Section>

      <Section title="Architecture">
        <p>
          One Next.js application. The frontend is a small client-side form; the backend is a
          single API route running on Node. There's no separate database server — the curated
          resource set and its precomputed embeddings live in the deploy bundle as a JSON file,
          regenerated by <code>npm run seed</code>.
        </p>
        <pre className="overflow-x-auto rounded-lg border border-slate-200 bg-slate-50 p-4 text-xs leading-relaxed text-slate-700">
{`Browser
   │  POST /api/recommend  { input }
   ▼
app/api/recommend/route.ts
   ├─► lib/ai.ts  ─── OpenAI text-embedding-3-small  (input embedding)
   ├─► lib/ai.ts  ─── OpenAI gpt-4o-mini + tool      (need extraction)
   │     ╰─ run in parallel ─╯
   ├─► lib/db.ts ─── data/resources.embedded.json   (precomputed embeddings)
   ├─► lib/recommend.ts                              (cosine + tags + diversify)
   └─► lib/ai.ts  ─── OpenAI gpt-4o-mini + tool      (per-resource why + next steps)

{ needs, recommendations[5], next_steps[2–4] }`}
        </pre>
        <p className="text-sm text-slate-600">
          Three OpenAI calls per request: 1 embedding + 2 chat completions. The first two run in
          parallel. Resource embeddings are computed once at seed time, never per request.
        </p>
      </Section>

      <Section title="Tech stack">
        <ul className="grid grid-cols-1 gap-2 text-sm sm:grid-cols-2">
          <Tech name="Frontend" detail="Next.js 16 (App Router), React 18, Tailwind CSS" />
          <Tech name="API" detail="Next.js Route Handlers (Node runtime)" />
          <Tech name="Embeddings" detail="OpenAI text-embedding-3-small (1536 dim)" />
          <Tech name="Need extraction" detail="OpenAI gpt-4o-mini + function calling (Zod-typed)" />
          <Tech name="Storage" detail="Static JSON bundled into the deploy" />
          <Tech name="Testing" detail="Vitest — 26 tests covering ranker + schema + scenarios" />
          <Tech name="Hosting" detail="Vercel (frontend + serverless API)" />
          <Tech name="Quality" detail="Link-health checker run before each milestone" />
        </ul>
      </Section>

      <Section title="How the AI works">
        <p className="font-semibold text-slate-700">1. Need extraction (GPT-4o-mini + function calling)</p>
        <p>
          The student's free-text input is sent to GPT-4o-mini with a typed tool definition. The
          model is required to return structured needs — each one with a <code>category</code>,{' '}
          <code>intensity</code> (1–5), the supporting evidence from the input, fine-grained{' '}
          <code>tags</code> (snake_case), and an <code>urgent</code> boolean for safety-critical
          situations. No free-form JSON, no parsing fragility.
        </p>
        <p className="font-semibold text-slate-700">2. Semantic retrieval (text-embedding-3-small)</p>
        <p>
          The same input is also embedded into a 1536-dimensional vector. Every resource has a
          precomputed embedding (name + category + description + tags). We compute cosine
          similarity between the input and every resource — fast because we only have{' '}
          {RESOURCE_COUNT} resources, no vector database needed.
        </p>
        <p className="font-semibold text-slate-700">3. Multi-signal ranking</p>
        <p>
          The final score combines four signals:
        </p>
        <ul className="list-disc space-y-1 pl-6 text-sm">
          <li>
            <strong>0.50 × normalized cosine similarity</strong> — semantic match
          </li>
          <li>
            <strong>0.25 × category match</strong> — does the resource's category match an
            extracted need?
          </li>
          <li>
            <strong>0.15 × tag overlap</strong> — share of extracted tags present in the resource's
            tags
          </li>
          <li>
            <strong>0.10 × urgency boost</strong> — student is urgent AND resource is flagged
            urgent
          </li>
        </ul>
        <p>
          After scoring, the top 5 are picked with category diversification (max 2 from any one
          category) so a student with multiple needs doesn't get a homogeneous result list.
        </p>
        <p className="font-semibold text-slate-700">4. Per-resource explanations + next steps</p>
        <p>
          The top 5 resources plus the extracted needs go back to GPT-4o-mini (again with a typed
          tool) which produces a 1–2 sentence explanation per resource and a 2–4 step ordered
          action plan referencing the student's words.
        </p>
      </Section>

      <Section title="User guide">
        <ol className="list-decimal space-y-2 pl-6">
          <li>
            Go to the <Link href="/" className="text-husky-purple underline">home page</Link>.
          </li>
          <li>
            Describe what's going on in your own words. Be honest about what's hard — "I'm
            stressed and behind in math" works better than "I need tutoring."
          </li>
          <li>
            Click <strong>Find resources</strong>. The first request takes ~3–5 seconds (three
            OpenAI calls).
          </li>
          <li>
            Read the <em>What we heard</em> section first — that's the AI's interpretation. If it's
            off, rephrase and try again.
          </li>
          <li>
            Click any recommendation to go to the official UW page. The <em>Your next steps</em>{' '}
            list is the recommended order to act on them.
          </li>
        </ol>
        <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">
          <strong>This isn't a crisis service.</strong> For emergencies call 911. For mental-health
          support call the Husky HelpLine (24/7). For safety concerns contact SafeCampus.
        </p>
      </Section>

      <Section title="Categories we cover">
        <ul className="grid grid-cols-1 gap-2 text-sm sm:grid-cols-2">
          {CATEGORIES.map((c) => (
            <li
              key={c}
              className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-slate-700"
            >
              {CATEGORY_LABELS[c]}
            </li>
          ))}
        </ul>
      </Section>

      <Section title="Built by">
        <p>
          CSS 382 — Introduction to AI · Spring 2026 · A two-person DYOP team. Source code on{' '}
          <a
            href="https://github.com/aryank09/UW-Compass"
            target="_blank"
            rel="noreferrer"
            className="text-husky-purple underline"
          >
            GitHub
          </a>
          .
        </p>
      </Section>

      <footer className="mt-12 border-t border-slate-200 pt-6 text-xs text-slate-500">
        <Link href="/" className="text-husky-purple hover:underline">
          ← Back to the app
        </Link>
      </footer>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="mb-3 text-xl font-semibold text-slate-800">{title}</h2>
      <div className="space-y-3 text-slate-700">{children}</div>
    </section>
  );
}

function Tech({ name, detail }: { name: string; detail: string }) {
  return (
    <li className="rounded-lg border border-slate-200 bg-white px-3 py-2">
      <span className="block text-xs font-semibold uppercase tracking-wide text-slate-500">
        {name}
      </span>
      <span className="text-slate-700">{detail}</span>
    </li>
  );
}
