import { ResourceWithEmbedding } from './types';

// Resources + precomputed embeddings, generated by `npm run seed`.
// The JSON is imported at build time, so the bundle includes all data —
// no runtime filesystem reads, no native modules, deploys cleanly to Vercel.
import embedded from '@/data/resources.embedded.json';

const RESOURCES = embedded as ResourceWithEmbedding[];

export function getAllResources(): ResourceWithEmbedding[] {
  return RESOURCES;
}

export function getResourceById(id: string): ResourceWithEmbedding | undefined {
  return RESOURCES.find((r) => r.id === id);
}

export function countResources(): number {
  return RESOURCES.length;
}
